### ISSUE TITLE
button overlapping on mobile

### ISSUE THREAD

**Issue by RohithChittibommala** [khannakshat7/Elektra#45] opened 2021-03-11 12:23 UTC
![image](https://user-images.githubusercontent.com/62145732/110786894-b3e69000-8292-11eb-889e-1a97627f62d6.png)

**Comment by tanishq-arya** [comment] 2021-03-11 13:24
Duplicate of #19

**Comment by CodesbyUnnati** [comment] 2021-03-13 12:50
Duplicate Issue, Please look for other issues.

**Closed by CodesbyUnnati** 2021-03-13 12:50 UTC
