### ISSUE TITLE
addition of welcome bot

### ISSUE THREAD

**Issue by Sloth-Panda** [khannakshat7/Elektra#14] opened 2021-03-09 07:29 UTC
this bot basically greets someone who opens up an issue or makes a pr for the first time in the repo

download the bot  from here 
https://github.com/apps/welcome

**Comment by Sloth-Panda** [comment] 2021-03-09 08:16
@anurag0singh ofcourse I want to work on it as I opened it .

**Comment by Sloth-Panda** [comment] 2021-03-09 10:03
@khannakshat7 can you please add gssoc'21 tag to the issue?!

**Comment by thesakshipandey** [comment] 2021-03-10 12:55
i Can do this issue effectively, Can you assign me this issue?

**Comment by rk05-lenavo** [comment] 2021-03-11 15:08
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by CodesbyUnnati** [comment] 2021-03-11 16:21
> Hey , I am participant in GSSOC'21. Can you please assign this to me?

Sorry, the issue is closed now. You can work on other issues or create one.

**Comment by CodesbyUnnati** [comment] 2021-03-11 16:21
> i Can do this issue effectively, Can you assign me this issue?


Sorry, the issue is closed now. You can work on other issues or create one.

**Comment by rk05-lenavo** [comment] 2021-03-12 10:24
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Closed** 2021-03-13 07:21 UTC
Labels: Level2, gssoc21
